// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.865
// This file will be auto-generated by 'templ-generate-heroicons'.

// It will contain Templ components for Heroicons used in your project.

// Example (if 'check_circle' is used and generated):

//

// package heroicons

//

// // Requires: templ v0.2.513 or later

// templ Outline_check_circle(attrs templ.Attributes) {

//	<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" { attrs... } class="size-6">

//		<path stroke-linecap="round" stroke-linejoin="round" d="M9 12.75 11.25 15 15 9.75M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z"/>

//	</svg>

// }

package heroicons

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// Placeholder to ensure the package exists before first generation.
// Remove this if templ-generate-heroicons creates the package declaration.
var _ = templruntime.GeneratedTemplate
