path: ./code
#path: ./code/tools
extensions: [.go, .templ, .js, .css, Makefile, .md, .air.toml]
#extensions: [.py, .md, .yaml]
output: embrygo
packages: [github.com/r-via/blitzkit]
exclude: [statics, www]
exclude_files: [_templ.go, package-lock.json, htmx.min.js]
gitignore: .gitignore
