// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.865
// Code generated by templ-heroicons-generator. DO NOT EDIT.

// Source: https://raw.githubusercontent.com/tailwindlabs/heroicons/master/optimized/24

// Version: master

package heroicons

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// Requires: templ v0.2.513 or later
// Web: https://heroicons.com/
// No icons were found or processed by the generation script.
var _ = templruntime.GeneratedTemplate
